spring:
  jackson:
    default-property-inclusion: non_null
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:8090
  boot:
    admin:
      client:
        url: http://localhost:8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*' ## only for training purposes
jwtSigningKey: "{cipher}c9f49977a841bfaa74b99ae0e487f113cc754b10a61e95439bec20e827022269"