server:
  port: 8001
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    stream:
      bindings:
        input:
          destination: payments-topic
          content-type: application/json
          groups: trips
baseCharge: "{cipher}c9f49977a841bfaa74b99ae0e487f113cc754b10a61e95439bec20e827022269"
