server:
  port: 8001
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    stream:
      bindings:
        input:
          destination: pending-payments-topic
          content-type: application/json
          groups: trips
baseCharge: 2000
