version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  configuration:
    image: training/configuration
    depends_on:
      - kafka
    environment:
      ACTIVE_PROFILE: production
      KAFKA_SERVER: kafka

